from data import names,students
from analysis import (calculate_mean,calculate_standarddeviation,topper,calculate_pass_percentage, calculate_correlation,predict_performance,calculate_outliers)
print("STUDENT PERFORMANCE ANALYZER")
print()

topper_name,topper_marks=topper(names,students)
print("Topper:")
print(topper_name)
print("Marks:")
print(topper_marks)
mean_marks=calculate_mean(students)
print("Average Marks:")
print(mean_marks)
print()
std_marks=calculate_standarddeviation(students)
print("Standard Deviation:")
print(std_marks)
print()
pass_percent=calculate_pass_percentage(students)
print("Pass Percentage:")
print(pass_percent)
print()
correlation_analysis= calculate_correlation(students)
print("Correlation Analysis:")
print(correlation_analysis)
print()
performance=predict_performance(names,students)
print("Performance Prediction:")
print(performance)   
print()                         
outlier=calculate_outliers(names,students)
print("Outlier Detection:")
print(outlier)
print()